### PR TITLE
Various improvements for stability and depth of ping

### PR DESCRIPTION
**Pull request by orsondmc**
@replydev good faith PR.

### CODE REVIEW

**Comment by replydev** [comment]
Never lose hope! Thank you, i will review your changes and merge soon.

**Comment by orsondmc** [comment]
Awesome. The loader detection could be better - would rather a string than enum in retrospect.

Any chance we could make it multi module? I'd like to use the ping protocol without the UI ;)

**Comment by orsondmc** [comment]
Perhaps we could collaborate on a good ping protocol lib as a separate repo?

**Comment by replydev** [comment]
Surely we could, but i do not have much time. Can we keep in touch on Discord?

**Comment by orsondmc** [comment]
Yeah lets keep in touch

**Comment by replydev** [comment]
Can i ask you why did you set compile options to JDK 11?

**Comment by orsondmc** [comment]
Can't remember off the top of my head but it was language features

**Pull request merged**
